-- ============================================================
-- lebeSsni v2.1.0 — Migration PostgreSQL (Supabase)
-- Execute CE fichier dans Supabase SQL Editor
-- ============================================================

-- 1. Activer pgcrypto pour gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 2. TABLES
-- ============================================================

-- Vendeurs (clients de la plateforme)
CREATE TABLE IF NOT EXISTS clients (
    id TEXT PRIMARY KEY DEFAULT replace(gen_random_uuid()::text, '-', ''),
    nom_boutique TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    ton_assistant TEXT DEFAULT 'chaleureux, rassurant, concis',
    duree_retention TEXT DEFAULT '24 heures',
    pixel_meta TEXT,
    pixel_tiktok TEXT,
    webhook_url TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Produits (crees par chaque vendeur)
CREATE TABLE IF NOT EXISTS produits (
    id TEXT PRIMARY KEY DEFAULT replace(gen_random_uuid()::text, '-', ''),
    client_id TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    nom TEXT NOT NULL,
    description TEXT,
    image_url TEXT NOT NULL,
    product_type TEXT NOT NULL CHECK(product_type IN (
        't-shirt', 'chemise', 'veste', 'manteau', 'pull',
        'pantalon', 'jean', 'short', 'jupe', 'robe',
        'basket', 'chaussures', 'accessoire', 'tenue_complete'
    )),
    mode_generation TEXT DEFAULT 'article_unique' CHECK(mode_generation IN (
        'article_unique', 'tenue_complete', 'sequentiel'
    )),
    landing_slug TEXT UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Generations d'images
CREATE TABLE IF NOT EXISTS generations (
    id TEXT PRIMARY KEY DEFAULT replace(gen_random_uuid()::text, '-', ''),
    produit_id TEXT REFERENCES produits(id) ON DELETE SET NULL,
    client_id TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    visitor_id TEXT,
    user_image_url TEXT,
    result_image_url TEXT,
    statut TEXT DEFAULT 'pending' CHECK(statut IN ('pending', 'processing', 'success', 'fail')),
    duree_generation_ms INTEGER,
    mode TEXT,
    product_type TEXT,
    quality_score REAL,
    created_at TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP
);

-- Abonnements / Credits
CREATE TABLE IF NOT EXISTS credits (
    id TEXT PRIMARY KEY DEFAULT replace(gen_random_uuid()::text, '-', ''),
    client_id TEXT NOT NULL UNIQUE REFERENCES clients(id) ON DELETE CASCADE,
    plan TEXT DEFAULT 'starter' CHECK(plan IN ('starter', 'pro', 'business')),
    credits_total INTEGER DEFAULT 50,
    credits_used INTEGER DEFAULT 0,
    credits_remaining INTEGER GENERATED ALWAYS AS (credits_total - credits_used) STORED,
    billing_period_start DATE DEFAULT CURRENT_DATE,
    billing_period_end DATE DEFAULT (CURRENT_DATE + INTERVAL '1 month'),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Analytics (journalier)
CREATE TABLE IF NOT EXISTS analytics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    visiteurs INTEGER DEFAULT 0,
    generations INTEGER DEFAULT 0,
    clics_achat INTEGER DEFAULT 0,
    UNIQUE(client_id, date)
);

-- ============================================================
-- 3. INDEX
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_produits_client ON produits(client_id);
CREATE INDEX IF NOT EXISTS idx_generations_client ON generations(client_id);
CREATE INDEX IF NOT EXISTS idx_generations_produit ON generations(produit_id);
CREATE INDEX IF NOT EXISTS idx_generations_expires ON generations(expires_at);
CREATE INDEX IF NOT EXISTS idx_analytics_client_date ON analytics(client_id, date);

-- ============================================================
-- 4. TRIGGERS
-- ============================================================

-- Auto-delete des generations expirees
CREATE OR REPLACE FUNCTION auto_delete_expired_fn()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM generations
    WHERE expires_at IS NOT NULL AND expires_at < NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS auto_delete_expired_generations ON generations;
CREATE TRIGGER auto_delete_expired_generations
    AFTER INSERT ON generations
    FOR EACH ROW
    EXECUTE FUNCTION auto_delete_expired_fn();

-- updated_at automatique
CREATE OR REPLACE FUNCTION update_updated_at_fn()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_clients_updated_at') THEN
        CREATE TRIGGER update_clients_updated_at
            BEFORE UPDATE ON clients
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_fn();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_produits_updated_at') THEN
        CREATE TRIGGER update_produits_updated_at
            BEFORE UPDATE ON produits
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_fn();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_credits_updated_at') THEN
        CREATE TRIGGER update_credits_updated_at
            BEFORE UPDATE ON credits
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_fn();
    END IF;
END $$;

-- ============================================================
-- 5. VERIFICATION
-- ============================================================
-- Execute ceci en bas du SQL Editor pour verifier :
-- SELECT table_name FROM information_schema.tables WHERE table_schema='public';
